title: Hotmess Lighthouses
email: liam@cloudcannon.com
description: >-
  Hotmess lighthouses site

baseurl: ""
url: ""

twitter_username: liambigelow
github_username:  bglw

theme: lighthouses-theme

collections:
  lighthouses:
    name: Lighthouses
    output: true
    permalink: /:slug/