[defaults]
big = false
lit = false # Whether the lighthouse is lit up or not
title = "Hello World" # This is a cool title huh

[defaults.beans--repeat]
rice = "tasty" # Rice
something = "else"

[standard]

[big]
big = true

[lit]
lit = true # Whether the lighthouse is lit up or not


